site_name: SREing
repo_url: https://github.com/SREing/sreing.github.io
repo_name: SREing/sreing.github.io
theme:
  name: material
  logo: assets/logo.png
  language: en
  favicon: assets/logo.png
  palette: 
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      media: "(prefers-color-scheme: dark)"
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.sections
    - search.suggest
    - search.highlight
    - search.share
plugins:
  - search
  - git-revision-date
